### ISSUE TITLE
"No tracking modules loaded by tracker..."

### ISSUE THREAD

**Issue by blthayer** [FSEC-Photovoltaics/pvrpm-lcoe#43]
My SAM case doesn't have trackers in it. However, if I include the `tracker` field in the yaml file (see below), I get an error.

```yaml
tracker: # only required for tracking systems, remove it not using trackers
  name: tracker
  can_fail: true
  can_repair: true
  can_monitor: true

```

Error message: `Error loading and verifying case: No tracking modules loaded by tracker defined in PVRPM configuration, please remove it if not using it.`

It seems like it would be more user friendly if this was a warning instead of an error. Something like 'Your SAM case contains no trackers, but there is a "tracker" section in the configuration file. Tracker configuration will be ignored, and no simulation related to trackers will be performed.'
